### ISSUE TITLE
 Message parsing error

### ISSUE THREAD

**Issue by guochunjiang** [namecheap/fast_mail_parser#10]
Message parsing error: Header cannot start with a space; it is likely an overhanging line from a previous header

**Comment by SaulTigh** [comment]
hey, sorry for late reply.
This behavior is by design, and most likely caused by malformed headers in email you are trying to parse.

You can refer to [implementation](https://github.com/staktrace/mailparse/blob/4657092f80248bae010e7715aeae3e27523b0a50/src/lib.rs#L345-L355) of library fast_mail_parser uses
